language: python
matrix:
  include:
    - name: "Python3.6 on Linux"
      python: 3.6
    - name: "Python on MacOs"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python on Windows"
      os: windows
      language: shell
      before_install:
        - choco install zip
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: pip3 install -r requirements.txt
script: 
  - python make.py 
  - pyinstaller BiliBiliHelper.spec
  - cp -r Conf ./dist/
  - cp -r Log ./dist/
  - cp -r Doc ./dist/
  - cd dist
  - zip -q -r BiliBiliHelper-${TRAVIS_OS_NAME}.zip *
deploy:
  provider: releases
  file: "dist/BiliBiliHelper-$TRAVIS_OS_NAME.zip"
  api_key: $GIT_REPO_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true