language: python
matrix:
  include:
    - name: "Python3.6 on Linux"
      python: 3.6
    - name: "Python on MacOs"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATHs
install: pip3 install -r requirements.txt
script: python3 make.py || pyinstaller BiliBiliHelper.spec