language: python
matrix:
  include:
    - name: "Python on Linux"
      env: BADGE=linux
    - name: "Python on MacOs"
      os: osx
      osx_image: xcode11
      language: shell
      env: BADGE=osx
    - name: "Python on Windows"
      os: windows
      language: shell
      before_install:
        - choco install zip
	- choco install python --version=3.7.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH BADGE=windows

install: pip3 install -r requirements.txt

script: 
  - python Make.py 
  - pyinstaller BiliBiliHelper.spec
  - cp -r Conf ./dist/
  - cp -r Log ./dist/
  - cp -r Doc ./dist/

before_deploy:
  - cd dist
  - if [[ $BADGE == "linux" ]]; then
      zip -r BiliBiliHelper-linux.zip *;
    fi
  - if [[ $BADGE == "osx" ]]; then
      zip -r BiliBiliHelper-osx.zip *;
    fi
  - if [[ $BADGE == "windows" ]]; then
      zip -r BiliBiliHelper-windows.zip *;
    fi
  - cd ..

deploy: 
  provider: releases
  file: "dist/BiliBiliHelper-$TRAVIS_OS_NAME.zip"
  api_key: $GIT_REPO_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true
