language: python
matrix:
  include:
    - name: "Python3.6 on Linux"
      python: "3.6"
    - name: "Python3.6 on MacOs"
      python: "3.6"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python3.6 on Windows"
      python: "3.6"
      os: windows
      language: shell
install: pip install -r requirements.txt